[env:esp32-s3-16r8]
platform = espressif32@~6.10.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    -DSPI_FREQUENCY=80000000
monitor_speed = 115200
lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.4.7
    bodmer/TJpg_Decoder@^1.1.0
    links2004/WebSockets@^2.4.2
upload_port = COM5
upload_speed = 921600